# Generated by Django 2.2.4 on 2019-08-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagement_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_make',
            new_name='make',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='model',
        ),
        migrations.RemoveField(
            model_name='car',
            name='at_branch',
        ),
    ]
