# Generated by Django 2.2.4 on 2019-08-13 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagement_api', '0003_auto_20190813_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='carmanagement_api.Branch'),
        ),
    ]
