# Generated by Django 2.2.4 on 2019-08-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagement_api', '0004_car_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='at_branch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='carmanagement_api.Driver'),
        ),
    ]
