# Generated by Django 2.2.4 on 2019-08-16 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('carmanagement_api', '0006_auto_20190813_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'carmanagement_api'), ('model', 'branch')), models.Q(('app_label', 'carmanagement_api'), ('model', 'driver')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='driver',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
