# Generated by Django 2.2.4 on 2019-08-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagement_api', '0007_auto_20190816_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='object_id',
            new_name='branch_driver_id',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='content_type',
            new_name='branch_driver_selector',
        ),
    ]
