# Generated by Django 2.2.4 on 2019-08-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagement_api', '0009_auto_20190816_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='branch_driver_id',
            new_name='currently_with_id',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='branch_driver_selector',
            new_name='currently_with_type',
        ),
    ]
