# Generated by Django 2.2.4 on 2019-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanagement_api', '0010_auto_20190816_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
